config/routes.rb
MyStore::Application.routes.draw do
  resources :users
  match '/signup',  to: 'users#new', via: 'get'

  resources :items do
  	get :upvote, on: :member
  	get :expensive, on: :collection
  end
 
end

app/models/cart.rb
class Cart < ActiveRecord::Base

	belongs_to :user
	has_many   :positions
	has_many   :items, through: :positions
	
end

app/models/item.rb
class Item < ActiveRecord::Base
	#attr_accessible :name, :price, :real, :weight, :description 

	validates :price, numericality: {greater_than: 0, allow_nil: true}
	validates :name, :description, presence: true

	has_many :positions
	has_many :carts, through: :positions
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :user

end

app/models/position.rb
class Position < ActiveRecord::Base

	attr_accessible :item_id, :cart_id, :quantity

	belongs_to :item
	belongs_to :cart
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  has_one :cart
  has_many :orders


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  private

  def render_error_404  
  	render file: "public/404.html", status: 404
  end 

  def render_error_403
	render file: "public/403.html", status: 404
	#render text: "Доступ только для администраторов магазина", status: 403 unless current.admin == true
	#render text: "Доступ только для администраторов магазина", status: 403 unless params[:admin]
  end 

  def check_if_admin
	render_error_403 unless params[:admin]
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	before_filter :find_item,      only: [:show, :edit, :update, :destroy, :upvote]
	#before_filter :check_if_admin, only: [:edit, :update, :destroy, :new, :create]

	def index
		@items = Item.all
	end

	def expensive
		@items = Item.where("price >1500")
		render "index"
	end

	# /items/1 GET
	def show
		unless @item
			render_error_404
		end
	end

	# /items/new GET
	def new
		@item = Item.new		
	end

	# /items/1/edit GET
	def edit
	end

	# /items POST
	def create
		@item = Item.create(item_params)
		if @item.errors.empty?
			redirect_to item_path(@item)
		else 
			render "edit"
		end
	end

	# /items/1 PUT
	def update
		@item.update_attributes(item_params)
		if @item.errors.empty?
			redirect_to item_path(@item)
		else 
			render "new"
		end
	end

	# /items/1 DELETE
	def destroy
		@item.destroy
		redirect_to action: "index"
	end

	def upvote
		@item.increment!(:votes_count)
		redirect_to action: :index		
	end

	private

		def find_item
			@item = Item.where(id: params[:id]).first
			render_error_404 unless @item
		end

	    def item_params
	      params.require(:item).permit(:name, :price, :real, :weight, :description )
	    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  	@users = User.all  	
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to @user
	else
		render 'new'
	end  	
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :password, 
 			 									:password_confirmation)  			
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<h1>Edit item</h1>

<%= form_for @item do |f| %>

	<p>Цена: </br><%= f.text_field     :price %></p>
	<p>Название: </br><%= f.text_field :name %></p>
	<p>Описание: </br><%= f.text_field :description %></p>
	<p>Вес: </br><%= f.text_field      :weight %></p>

	<p><%= f.submit "Изменить товар" %></p>
<% end %>

app/views/items/index.html.erb
<h1>Items</h1>

<% if @items.empty? %>
	<b>No items in store</b>
<% else %>
<table>
	<tr>
		<th>item id</th>
		<th>Name</th>
		<th>Price</th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

	<% @items.each do |i| %>

		<tr>
			<td><%= i.id %></td>
			<td><%= link_to i.name, item_path(i) %></td>
			<td><%= i.price %> руб.</td>
			<td><%= link_to "Удалить", i, method: :delete, data: { confirm: "Точно удалить"} %></td>
			<td>Рейтинг: <%= i.votes_count %>, <%= link_to "+", upvote_item_path(i) %></td>
			<td><input type="text" name="number_items" size="2" value="1"></td>
			<td><span class="addItemToCart">Добавить в корзину</span></td>
		</tr>

	<% end %>

</table>

<% end %>

app/views/items/new.html.erb
<h1>Create new item</h1>

<%= form_for @item do |f| %>

	<p>Цена: </br><%= f.text_field     :price %></p>
	<p>Название: </br><%= f.text_field :name %></p>
	<p>Описание: </br><%= f.text_field :description %></p>
	<p>Вес: </br><%= f.text_field      :weight %></p>

	<p><%= f.submit "Создать товар" %></p>
<% end %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<ul>
	<li><%=@item.price %>руб.</li>
	<li><%=@item.description %>руб.</li>
	<li>Вес: <%=@item.weight %>кг.</li>
</ul>

app/views/layouts/_footer.html.erb
<footer class="footer">

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStore</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= yield %>

<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>All users</h1>

<% if @users.empty? %>
	<b>No users in store</b>
<% else %>
<table>
	<tr>
		<th>item id</th>
		<th>User name</th>
		<th>User email</th>
		<th></th>
		<th></th>
	</tr>

	<% @users.each do |i| %>

		<tr>
			<td><%= i.id %></td>
			<td><%= link_to i.name, user_path(i) %></td>
			<td><%= i.email %> руб.</td>
			<td></td>
			<td></td>
		</tr>

	<% end %>

</table>

<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <p><%= f.label :name %></p>
      <p><%= f.text_field :name %></p>

      <p><%= f.label :email %></p>
      <p><%= f.text_field :email %></p>

      <p><%= f.label :password %></p>
      <p><%= f.password_field :password %></p>

      <p><%= f.label :password_confirmation, "Confirmation" %></p>
      <p><%= f.password_field :password_confirmation %></p>

      <p><%= f.submit "Create my account", class: "btn btn-large btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>